spring:
    redis:
      database: 0
      password: test@2018
      cluster:
          nodes: 172.18.0.1:7000,172.18.0.1:7001,172.18.0.1:7002,172.18.0.1:7003,172.18.0.1:7004,172.18.0.1:7005
          max-redirects: 3
          # 重试次数
          max-attempts: 5
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 16
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 8
          timeout: 1000
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.18.0.3:3306/css?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: gms
        password: mIheOLbkQmQV8aeG
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        stat-view-servlet:
            enabled: true
            url-pattern: /druid/*
            login-username: mapper
            login-password: mapper
        filter:
            stat:
                log-slow-sql: true
                slow-sql-millis: 1000
                merge-sql: true
            wall:
                config:
                    multi-statement-allow: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

second-net:
  activation-css: 210

image-path: /data/upload/images/

server-ip: https://api.gmsjk.com/